name: Accessibility Metadata Display Guide for Digital Publications
description: Issue related to the "Accessibility Metadata Display Guide for Digital Publications" report 
labels: a11y-display-guide
body: 
  - type: markdown
    attributes:
     value: "## Issue on the Accessibility Metadata Display Guide for Digital Publications report"
  - type: markdown
    attributes:
     value: __Before opening an issue__, please check that it has not already been resolved in the [latest editor's draft](https://w3c.github.io/publ-a11y/metadata-display-guide/)
  - type: input
    id: section
    attributes:
      label: Section
      description: Please provide a link to the relevant section of the report
    validations:
      required: false 
  - type: textarea
    id: problem
    attributes:
      label: Describe the problem
      description: What is not working? What would you like to see improved? For bug reports, cite the relevant text from the report.
    validations:
      required: true
  - type: textarea
    id: fix
    attributes:
      label: Describe the fix or new feature you propose
    validations:
      required: false
