name: Expressing Accessibility Metadata in the EPUB Package Document
description: Issue related to Expressing Accessibility Metadata in the EPUB Package Document
labels: package-metadata-guide
body: 
  - type: markdown
    attributes:
     value: "## Issue on the [Expressing Accessibility Metadata in the EPUB Package Document](https://w3c.github.io/publ-a11y/package-metadata-authoring-guide/)"
  - type: markdown
    attributes:
     value: __Before opening an issue__, please check that it has not already been resolved in the [latest editor's draft](https://w3c.github.io/publ-a11y/package-metadata-authoring-guide/)
  - type: input
    id: section
    attributes:
      label: Section
      description: Please provide a link to the relevant section of the report
    validations:
      required: false 
  - type: textarea
    id: problem
    attributes:
      label: Describe the problem
      description: What would you like to see improved? For bug reports, cite the relevant text from the specification.
    validations:
      required: true
  - type: textarea
    id: fix
    attributes:
      label: Describe the fix or new feature you propose
    validations:
      required: false
