name: General issue template
description: Issues on reports published by the accessibility task force of the Publishing Community Group
body: 
  - type: markdown
    attributes:
     value: "## Before opening an issue"
  - type: markdown
    attributes:
     value: |
       This repository is for issues with reports published by the accessibility task force of the Publishing Community Group. Please use the more appropriate issue template for questions/issues related to the following documents.
       * [Accessibility Metadata Display Guide for Digital Publications](https://www.w3.org/publishing/a11y/metadata-display-guide/guidelines/)
       * [Display Techniques for EPUB Accessibility Metadata](https://www.w3.org/publishing/a11y/metadata-display-guide/techniques/epub/)
       * [Display Techniques for ONIX Accessibility Metadata](https://www.w3.org/publishing/a11y/metadata-display-guide/techniques/onix/)
       * [Accessibility Metadata Crosswalk](https://www.w3.org/2021/a11y-discov-vocab/latest/crosswalk/)
       * [Expressing Accessibility Metadata in the EPUB Package Document](https://w3c.github.io/publ-a11y/package-metadata-authoring-guide/)
  - type: textarea
    id: problem
    attributes:
      label: Describe the problem
      description: What is not working? What would you like to see improved? For bug reports, cite the relevant text from the report.
    validations:
      required: true
  - type: textarea
    id: fix
    attributes:
      label: Describe the fix or new feature you propose
    validations:
      required: false
